import { Types } from "mongoose";

export type Employee = {
  userId: Types.ObjectId;
  employeeId: number;
  employeeEmail: string;
  branch: Types.ObjectId;
  branchEmail: string;
  companyEmail: string;
  employeeName: string;
  joiningDate: string;
  employeeType: "fullTime" | "partTime" | "seasonal" | "temporary";
  employeeDesignation: "manager" | "accountant" | "fieldOfficer";
  phoneNo: string;
  employeeNid: string;
  presentAddress: string;
  permanentAddress: string;
  fatherName: string;
  motherName: string;
  bloodGroup: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-";
  degree: string;
  basicSalary: number;
  mobileBill: number;
  conveyanceAllowance: number;
  medicalAllowance: number;
  houseRent: number;
  incentiveBonus: number;
  others?: number;
  professionalTax: number;
  incomeTax: number;
  providentFund: number;
  totalSalary: number;
  profileImage: string;
  attachments: string[];
};
