import { Types } from "mongoose";

export type Employee = {
  employeeId: string;
  employeeEmail: string;
  userId: Types.ObjectId;
  branchEmail: string;
  employeeName: string;
  joiningDate: string;
  employeeType: string;
  phoneNo: string;
  employeeNid: string;
  presentAddress: string;
  fatherName: string;
  motherName: string;
  bloodGroup: string;
  degree: string;
  basicSalary: number;
  mobileBill: number;
  conveyanceAllowance: number;
  medicalAllowance: number;
  houseRent: number;
  incentiveBonus: number;
  others: number;
  professionalTax: number;
  incomeTax: number;
  providentFund: number;
  totalSalary: number;
  profileImage: string;
};
